services:
  app:
    image: phongthanhphong/grade-portal-tele:latest
    env_file:
      - ./config/.env
    ports:
      - "8080:8080" 
    container_name: grade-portal-tele
    restart: unless-stopped
