services:
  app:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: test-docker-build
    env_file:
      - .env
    ports:
      - "8080:8080" 
    container_name: grade-portal-tele
    restart: unless-stopped 
